package web

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// WafDetectTool 通过探针请求与响应特征推测 WAF。
type WafDetectTool struct{}

func (t *WafDetectTool) Name() string { return "waf_detect" }

func (t *WafDetectTool) Description() string {
	return "向目标 URL 发送 SQLi/XSS 等探针请求，根据响应头与正文特征推测 WAF（如 Cloudflare、ModSecurity）。输入: URL"
}

var wafProbes = []struct {
	Name   string
	Path   string
	Header map[string]string
}{
	{"sqli_quote", "", map[string]string{"X-Forwarded-For": "' OR '1'='1"}},
	{"sqli_union", "?id=1' UNION SELECT NULL--", nil},
	{"xss_script", "?q=<script>alert(1)</script>", nil},
	{"path_traversal", "?file=../../etc/passwd", nil},
}

type wafSignature struct {
	ID      string   `json:"id"`
	Hints   []string `json:"hints"`
	InBody  []string `json:"in_body,omitempty"`
	InHeader []string `json:"in_header,omitempty"`
}

var wafSignatures = []wafSignature{
	{"cloudflare", []string{"Cloudflare"}, []string{"Attention Required", "cf-browser-verification", "cloudflare"}, []string{"cf-ray", "cf-cache-status", "server"}},
	{"aws_waf", []string{"AWS WAF"}, []string{"Request blocked", "AWS WAF"}, []string{"x-amzn-requestid", "x-amz-cf-id"}},
	{"akamai", []string{"Akamai"}, []string{"AkamaiGHost", "Reference #"}, []string{"akamai", "x-akamai"}},
	{"modsecurity", []string{"ModSecurity"}, []string{"ModSecurity", "NOYB", "Not Acceptable"}, []string{"mod_security"}},
	{"imperva", []string{"Incapsula"}, []string{"incapsula", "_incapsula_resource"}, []string{"x-cdn", "x-iinfo"}},
	{"sucuri", []string{"Sucuri"}, []string{"sucuri", "Cloudproxy"}, []string{"x-sucuri", "x-sucuri-id"}},
	{"barracuda", []string{"Barracuda"}, []string{"barra_counter_session"}, nil},
	{"fortiweb", []string{"FortiWeb"}, []string{"FortiWeb", ".fgd_icon"}, []string{"fortiwafsid"}},
	{"f5_bigip", []string{"F5 BIG-IP"}, []string{"The requested URL was rejected", "support ID"}, []string{"x-wa-info", "BigIP"}},
	{"wordfence", []string{"Wordfence"}, []string{"wordfence", "Generated by Wordfence"}, nil},
}

func matchWAF(body string, headers http.Header) []map[string]string {
	bodyLower := strings.ToLower(body)
	matched := make([]map[string]string, 0)
	seen := map[string]struct{}{}

	headerBlob := strings.Builder{}
	for k, vs := range headers {
		kk := strings.ToLower(k)
		for _, v := range vs {
			headerBlob.WriteString(kk)
			headerBlob.WriteString(": ")
			headerBlob.WriteString(strings.ToLower(v))
			headerBlob.WriteByte('\n')
		}
	}
	hb := headerBlob.String()

	for _, sig := range wafSignatures {
		for _, hint := range sig.Hints {
			score := 0
			hl := strings.ToLower(hint)
			for _, sub := range sig.InBody {
				if strings.Contains(bodyLower, strings.ToLower(sub)) {
					score += 2
				}
			}
			for _, sub := range sig.InHeader {
				if strings.Contains(hb, strings.ToLower(sub)) {
					score += 2
				}
			}
			if score > 0 {
				id := sig.ID
				if _, ok := seen[id]; !ok {
					seen[id] = struct{}{}
					matched = append(matched, map[string]string{
						"waf":       hl,
						"signature": id,
						"score":     fmt.Sprintf("%d", score),
					})
				}
				break
			}
		}
	}
	return matched
}

func (t *WafDetectTool) Call(ctx context.Context, input string) (string, error) {
	target, err := normalizeBaseURL(input)
	if err != nil {
		// normalizeBaseURL 要求完整 URL；若只有 host，补 /
		input = strings.TrimSpace(input)
		if strings.HasPrefix(input, "http") {
			return "", err
		}
		target, err = normalizeBaseURL("https://" + input)
		if err != nil {
			return "", err
		}
	}

	client := &http.Client{Timeout: 15 * time.Second}
	results := make([]map[string]any, 0)

	for _, probe := range wafProbes {
		u := target
		if probe.Path != "" {
			if strings.HasPrefix(probe.Path, "?") {
				u = strings.TrimSuffix(target, "/") + probe.Path
			} else {
				u = strings.TrimSuffix(target, "/") + "/" + strings.TrimPrefix(probe.Path, "/")
			}
		}
		req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
		if err != nil {
			continue
		}
		req.Header.Set("User-Agent", "Mozilla/5.0 SecBot-WAFProbe/1.0")
		for k, v := range probe.Header {
			req.Header.Set(k, v)
		}
		resp, err := client.Do(req)
		if err != nil {
			results = append(results, map[string]any{
				"probe": probe.Name, "error": err.Error(),
			})
			continue
		}
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 256*1024))
		_ = resp.Body.Close()
		bodyStr := string(body)
		matched := matchWAF(bodyStr, resp.Header)

		hdr := make(map[string]string)
		for k, vs := range resp.Header {
			if len(vs) > 0 {
				hdr[k] = vs[0]
			}
		}
		results = append(results, map[string]any{
			"probe":       probe.Name,
			"url":         u,
			"status_code": resp.StatusCode,
			"waf_matches": matched,
			"headers_sample": map[string]string{
				"server":          resp.Header.Get("Server"),
				"cf-ray":          resp.Header.Get("CF-RAY"),
				"x-sucuri-id":     resp.Header.Get("X-Sucuri-ID"),
				"x-amzn-requestid": resp.Header.Get("x-amzn-RequestId"),
			},
			"body_preview": trimPreview(bodyStr, 400),
		})
	}

	summary := map[string]any{
		"url":     target,
		"probes":  results,
		"note":    "基于启发式匹配，非确定性结论；需结合人工与更多探针验证。",
	}
	out, _ := json.MarshalIndent(summary, "", "  ")
	return string(out), nil
}

func trimPreview(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
