package planning

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/tmc/langchaingo/llms"
	"github.com/tmc/langchaingo/tools"
)

// PlanStep represents a single step in a plan.
type PlanStep struct {
	ID          string   `json:"id"`
	Description string   `json:"description"`
	Tool        string   `json:"tool,omitempty"`  // Tool to use (empty = LLM-only step)
	ToolInput   string   `json:"tool_input,omitempty"`
	DependsOn   []string `json:"depends_on,omitempty"` // IDs of prerequisite steps
}

// Plan is a structured plan generated by the planner.
type Plan struct {
	Goal  string     `json:"goal"`
	Steps []PlanStep `json:"steps"`
}

// StepResult holds the result of executing a plan step.
type StepResult struct {
	StepID  string `json:"step_id"`
	Output  string `json:"output"`
	Success bool   `json:"success"`
	Error   string `json:"error,omitempty"`
}

// PlanResult holds the complete execution result.
type PlanResult struct {
	Plan         *Plan        `json:"plan"`
	StepResults  []StepResult `json:"step_results"`
	FinalOutput  string       `json:"final_output"`
	AllSucceeded bool         `json:"all_succeeded"`
}

// Planner decomposes goals into structured plans and executes them.
type Planner struct {
	LLM      llms.Model
	Tools    []tools.Tool
	MaxSteps int
}

// NewPlanner creates a new planning pattern instance.
func NewPlanner(llm llms.Model, toolList []tools.Tool, maxSteps int) *Planner {
	if maxSteps <= 0 {
		maxSteps = 10
	}
	return &Planner{
		LLM:      llm,
		Tools:    toolList,
		MaxSteps: maxSteps,
	}
}

// CreatePlan uses the LLM to decompose a goal into a structured plan.
func (p *Planner) CreatePlan(ctx context.Context, goal string) (*Plan, error) {
	toolDescs := p.toolDescriptions()

	prompt := fmt.Sprintf(`You are a task planner. Decompose the following goal into a step-by-step plan.

Goal: %s

Available tools:
%s

Respond in JSON format:
{
  "goal": "the original goal",
  "steps": [
    {
      "id": "step_1",
      "description": "what this step does",
      "tool": "tool name or empty string if LLM-only",
      "tool_input": "input for the tool",
      "depends_on": ["step_ids this depends on"]
    }
  ]
}

Rules:
- Maximum %d steps
- Each step should be atomic and clear
- Use tools when appropriate, leave tool empty for reasoning/synthesis steps
- The final step should synthesize or present the result
- Respond with valid JSON only.`, goal, toolDescs, p.MaxSteps)

	resp, err := llms.GenerateFromSinglePrompt(ctx, p.LLM, prompt,
		llms.WithTemperature(0.1),
	)
	if err != nil {
		return nil, fmt.Errorf("plan generation failed: %w", err)
	}

	// Parse the plan
	resp = extractJSON(resp)
	var plan Plan
	if err := json.Unmarshal([]byte(resp), &plan); err != nil {
		return nil, fmt.Errorf("failed to parse plan JSON: %w (response: %s)", err, resp)
	}

	if plan.Goal == "" {
		plan.Goal = goal
	}
	return &plan, nil
}

// ExecutePlan executes a plan step by step, respecting dependencies.
func (p *Planner) ExecutePlan(ctx context.Context, plan *Plan) (*PlanResult, error) {
	result := &PlanResult{
		Plan:         plan,
		StepResults:  make([]StepResult, 0, len(plan.Steps)),
		AllSucceeded: true,
	}

	toolMap := make(map[string]tools.Tool)
	for _, t := range p.Tools {
		toolMap[strings.ToLower(t.Name())] = t
	}

	stepOutputs := make(map[string]string) // step_id -> output

	for _, step := range plan.Steps {
		// Build context from dependent steps
		var depContext strings.Builder
		for _, dep := range step.DependsOn {
			if out, ok := stepOutputs[dep]; ok {
				fmt.Fprintf(&depContext, "[%s result]: %s\n", dep, out)
			}
		}

		var output string
		var err error

		if step.Tool != "" {
			// Execute tool
			tool, ok := toolMap[strings.ToLower(step.Tool)]
			if ok {
				toolInput := step.ToolInput
				if depContext.Len() > 0 {
					toolInput = fmt.Sprintf("%s\nContext: %s", toolInput, depContext.String())
				}
				output, err = tool.Call(ctx, toolInput)
			} else {
				err = fmt.Errorf("tool %q not found", step.Tool)
			}
		} else {
			// LLM-only step
			prompt := fmt.Sprintf("Task: %s\n\nGoal: %s\n", step.Description, plan.Goal)
			if depContext.Len() > 0 {
				prompt += fmt.Sprintf("\nPrevious results:\n%s", depContext.String())
			}
			output, err = llms.GenerateFromSinglePrompt(ctx, p.LLM, prompt)
		}

		sr := StepResult{
			StepID:  step.ID,
			Success: err == nil,
			Output:  output,
		}
		if err != nil {
			sr.Error = err.Error()
			result.AllSucceeded = false
		}

		result.StepResults = append(result.StepResults, sr)
		stepOutputs[step.ID] = output
	}

	// Final output is from the last step
	if len(result.StepResults) > 0 {
		result.FinalOutput = result.StepResults[len(result.StepResults)-1].Output
	}

	return result, nil
}

// PlanAndExecute combines planning and execution in one call.
func (p *Planner) PlanAndExecute(ctx context.Context, goal string) (*PlanResult, error) {
	plan, err := p.CreatePlan(ctx, goal)
	if err != nil {
		return nil, err
	}
	return p.ExecutePlan(ctx, plan)
}

func (p *Planner) toolDescriptions() string {
	if len(p.Tools) == 0 {
		return "(no tools available - all steps should be LLM-only)"
	}
	var sb strings.Builder
	for _, t := range p.Tools {
		fmt.Fprintf(&sb, "- %s: %s\n", t.Name(), t.Description())
	}
	return sb.String()
}

func extractJSON(s string) string {
	start := strings.Index(s, "{")
	end := strings.LastIndex(s, "}")
	if start >= 0 && end > start {
		return s[start : end+1]
	}
	return s
}
